Repository socialsoftware/mono2micro, pull requests merged in 2020-08, with the labels that each got.

#23 read datafiles and write with jackson
  backend/src/main/java/pt/ist/socialsoftware/mono2micro/controller/AnalysisController.java
  backend/src/main/java/pt/ist/socialsoftware/mono2micro/controller/CodebaseController.java
  backend/src/main/java/pt/ist/socialsoftware/mono2micro/domain/Codebase.java
  backend/src/main/java/pt/ist/socialsoftware/mono2micro/domain/Controller.java
  backend/src/main/java/pt/ist/socialsoftware/mono2micro/domain/Dendrogram.java
  backend/src/main/java/pt/ist/socialsoftware/mono2micro/domain/Graph.java
  backend/src/main/java/pt/ist/socialsoftware/mono2micro/manager/CodebaseManager.java
  backend/src/main/java/pt/ist/socialsoftware/mono2micro/utils/Utils.java
  backend/src/main/resources/application.properties
  frontend/src/components/codebase/Codebases.js
Labels: needs review

#21 Feature/prepare be to receive dynamic data
  backend/src/main/java/pt/ist/socialsoftware/mono2micro/controller/AnalysisController.java
  backend/src/main/java/pt/ist/socialsoftware/mono2micro/controller/CodebaseController.java
  backend/src/main/java/pt/ist/socialsoftware/mono2micro/controller/DendrogramController.java
  backend/src/main/java/pt/ist/socialsoftware/mono2micro/domain/Cluster.java
  backend/src/main/java/pt/ist/socialsoftware/mono2micro/domain/Codebase.java
  backend/src/main/java/pt/ist/socialsoftware/mono2micro/domain/Controller.java
  backend/src/main/java/pt/ist/socialsoftware/mono2micro/domain/Dendrogram.java
  backend/src/main/java/pt/ist/socialsoftware/mono2micro/domain/Graph.java
  backend/src/main/java/pt/ist/socialsoftware/mono2micro/dto/AccessDto.java
  backend/src/main/java/pt/ist/socialsoftware/mono2micro/dto/AccessWithFrequencyDto.java
  backend/src/main/java/pt/ist/socialsoftware/mono2micro/dto/ControllerDto.java
  backend/src/main/java/pt/ist/socialsoftware/mono2micro/dto/CutInfoDto.java
  backend/src/main/java/pt/ist/socialsoftware/mono2micro/dto/SequenceDto.java
  backend/src/main/java/pt/ist/socialsoftware/mono2micro/dto/TraceDto.java
  backend/src/main/java/pt/ist/socialsoftware/mono2micro/manager/CodebaseManager.java
  backend/src/main/java/pt/ist/socialsoftware/mono2micro/utils/ControllerTracesIterator.java
  backend/src/main/java/pt/ist/socialsoftware/mono2micro/utils/Metrics.java
  backend/src/main/java/pt/ist/socialsoftware/mono2micro/utils/Utils.java
  backend/src/main/java/pt/ist/socialsoftware/mono2micro/utils/deserializers/AccessDtoDeserializer.java
  backend/src/main/java/pt/ist/socialsoftware/mono2micro/utils/deserializers/AccessWithFrequencyDtoDeserializer.java
  backend/src/main/java/pt/ist/socialsoftware/mono2micro/utils/deserializers/ControllerDtoDeserializer.java
  backend/src/main/java/pt/ist/socialsoftware/mono2micro/utils/deserializers/CutInfoDtoDeserializer.java
  backend/src/main/java/pt/ist/socialsoftware/mono2micro/utils/deserializers/SequenceDtoDeserializer.java
  backend/src/main/java/pt/ist/socialsoftware/mono2micro/utils/serializers/CutInfoDtoSerializer.java
  backend/src/main/resources/specific.properties.example
  frontend/src/components/codebase/Codebases.js
  frontend/src/services/RepositoryService.js
Labels: needs review

#25 Rework/graph
  backend/pom.xml
  backend/src/main/java/pt/ist/socialsoftware/mono2micro/controller/AnalysisController.java
  backend/src/main/java/pt/ist/socialsoftware/mono2micro/controller/ClusterController.java
  backend/src/main/java/pt/ist/socialsoftware/mono2micro/controller/DendrogramController.java
  backend/src/main/java/pt/ist/socialsoftware/mono2micro/domain/Controller.java
  backend/src/main/java/pt/ist/socialsoftware/mono2micro/domain/Dendrogram.java
  backend/src/main/java/pt/ist/socialsoftware/mono2micro/domain/Graph.java
  backend/src/main/java/pt/ist/socialsoftware/mono2micro/dto/AccessDto.java
  backend/src/main/java/pt/ist/socialsoftware/mono2micro/dto/AccessWithFrequencyDto.java
  backend/src/main/java/pt/ist/socialsoftware/mono2micro/dto/SequenceDto.java
  backend/src/main/java/pt/ist/socialsoftware/mono2micro/dto/TraceDto.java
  backend/src/main/java/pt/ist/socialsoftware/mono2micro/manager/CodebaseManager.java
  backend/src/main/java/pt/ist/socialsoftware/mono2micro/utils/Metrics.java
  backend/src/main/java/pt/ist/socialsoftware/mono2micro/utils/deserializers/AccessDtoDeserializer.java
  backend/src/main/java/pt/ist/socialsoftware/mono2micro/utils/deserializers/AccessWithFrequencyDtoDeserializer.java
  backend/src/main/java/pt/ist/socialsoftware/mono2micro/utils/deserializers/ControllerDeserializer.java
  backend/src/main/java/pt/ist/socialsoftware/mono2micro/utils/deserializers/SequenceDtoDeserializer.java
  backend/src/main/java/pt/ist/socialsoftware/mono2micro/utils/serializers/AccessDtoSerializer.java
  backend/src/main/java/pt/ist/socialsoftware/mono2micro/utils/serializers/ControllerSerializer.java
  backend/src/main/java/pt/ist/socialsoftware/mono2micro/utils/serializers/GraphSerializer.java
  frontend/src/components/view/ClusterView.js
  frontend/src/components/view/EntityOperationsMenu.js
  frontend/src/components/view/EntityView.js
  frontend/src/components/view/TransactionView.js
Labels: enhancement, in progress, needs review

#26 frontendBugFixes
  backend/src/main/java/pt/ist/socialsoftware/mono2micro/domain/Graph.java
  backend/src/main/java/pt/ist/socialsoftware/mono2micro/utils/Metrics.java
  frontend/package.json
  frontend/src/components/analysis/Analyser.js
  frontend/src/components/dendrogram/Dendrograms.js
  frontend/src/components/util/VisNetwork.js
  frontend/src/components/view/ClusterView.js
  frontend/src/components/view/EntityOperationsMenu.js
  frontend/src/components/view/EntityView.js
  frontend/src/components/view/TransactionView.js
  frontend/src/components/view/Views.js
Labels: bug, enhancement, in progress

#27 Feature/typescript
  frontend/package.json
  frontend/src/components/App.js
  frontend/src/components/Header.js
  frontend/src/components/analysis/Analyser.tsx
  frontend/src/components/analysis/Analysis.js
  frontend/src/components/codebase/Codebase.js
  frontend/src/components/codebase/Codebases.js
  frontend/src/components/dendrogram/Dendrogram.js
  frontend/src/components/dendrogram/Dendrograms.js
  frontend/src/components/profile/Profiles.js
  frontend/src/components/util/ModalMessage.js
  frontend/src/components/view/ClusterOperationsMenu.js
  frontend/src/components/view/ClusterView.js
  frontend/src/components/view/EntityOperationsMenu.js
  frontend/src/components/view/EntityView.js
  frontend/src/components/view/TransactionOperationsMenu.js
  frontend/src/components/view/TransactionView.js
  frontend/src/components/view/Views.js
  frontend/src/react-app-env.d.ts
  frontend/tsconfig.json
Labels: enhancement

#29 Frontend bug fixes part2
  frontend/src/components/Home.js
  frontend/src/components/codebase/Codebases.js
  frontend/src/components/dendrogram/Dendrogram.js
  frontend/src/components/dendrogram/Dendrograms.js
  frontend/src/components/profile/Profiles.js
  frontend/src/components/view/EntityView.js
Labels: needs review, pending

#30 Feature/traces reduction
  backend/src/main/java/pt/ist/socialsoftware/mono2micro/controller/AnalysisController.java
  backend/src/main/java/pt/ist/socialsoftware/mono2micro/controller/DendrogramController.java
  backend/src/main/java/pt/ist/socialsoftware/mono2micro/domain/Codebase.java
  backend/src/main/java/pt/ist/socialsoftware/mono2micro/domain/Dendrogram.java
  backend/src/main/java/pt/ist/socialsoftware/mono2micro/domain/Graph.java
  backend/src/main/java/pt/ist/socialsoftware/mono2micro/dto/AnalyserDto.java
  backend/src/main/java/pt/ist/socialsoftware/mono2micro/dto/TraceDto.java
  backend/src/main/java/pt/ist/socialsoftware/mono2micro/utils/Constants.java
  backend/src/main/java/pt/ist/socialsoftware/mono2micro/utils/ControllerTracesIterator.java
  frontend/public/index.html
  frontend/src/components/App.js
  frontend/src/components/analysis/Analyser.tsx
  frontend/src/components/codebase/Codebases.js
  frontend/src/components/dendrogram/Dendrogram.js
  frontend/src/components/dendrogram/Dendrograms.js
  frontend/src/index.js
  frontend/src/services/RepositoryService.js
Labels: needs review, pending

#32 added stuff
  collectors/dynamic-collection/aspects/AbstractOperationExecutionAspect.java
  collectors/dynamic-collection/aspects/GettersAndSetters.java
  collectors/dynamic-collection/compressors/ZipCompressor.java
  collectors/dynamic-collection/configs/aop.xml
  collectors/dynamic-collection/configs/kieker.monitoring.properties.example
  collectors/dynamic-collection/scripts/pom.xml
  collectors/dynamic-collection/scripts/src/main/java/ControllerEntities.java
  collectors/dynamic-collection/scripts/src/main/java/ControllerEntitiesJSONMerger.java
  collectors/dynamic-collection/scripts/src/main/java/JSONCompactor.java
  collectors/dynamic-collection/scripts/src/main/java/JSONGenerator.java
  collectors/dynamic-collection/scripts/src/main/java/JSONReducer.java
  collectors/dynamic-collection/scripts/src/main/java/deserializers/AccessDeserializer.java
  collectors/dynamic-collection/scripts/src/main/java/deserializers/AccessWithFrequencyDeserializer.java
  collectors/dynamic-collection/scripts/src/main/java/deserializers/SequenceDeserializer.java
  collectors/dynamic-collection/scripts/src/main/java/domain/Access.java
  collectors/dynamic-collection/scripts/src/main/java/domain/AccessWithFrequency.java
  collectors/dynamic-collection/scripts/src/main/java/domain/Functionality.java
  collectors/dynamic-collection/scripts/src/main/java/domain/Sequence.java
  collectors/dynamic-collection/scripts/src/main/java/domain/Trace.java
  collectors/dynamic-collection/scripts/src/main/java/domain/TraceWithAccesses.java
  collectors/dynamic-collection/scripts/src/main/java/domain/TraceWithSequences.java
  collectors/dynamic-collection/scripts/src/main/java/serializers/AccessSerializer.java
  collectors/dynamic-collection/scripts/src/main/java/serializers/AccessWithFrequencySerializer.java
  collectors/dynamic-collection/scripts/src/main/java/serializers/FunctionalitySerializer.java
  collectors/dynamic-collection/scripts/src/main/java/serializers/SequenceSerializer.java
  collectors/dynamic-collection/scripts/src/main/java/serializers/TraceWithAccessesSerializer.java
  collectors/dynamic-collection/scripts/src/main/java/serializers/TraceWithSequencesSerializer.java
  collectors/dynamic-collection/scripts/src/main/java/utils/Utils.java
Labels: needs review
